# Create ns dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev
spec: {}
status: {}
# Jane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
  apiGroup: ""
roleRef:
  kind: Role
  name: ServiceAccount
  apiGroup: rbac.authorization.k8s.io
# Ken
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
  apiGroup: ""
roleRef:
  kind: Role
  name: ServiceAccount
  apiGroup: rbac.authorization.k8s.io