---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-—Åluster-admin
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
