apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
            name: nginx
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          imagePullPolicy: IfNotPresent
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          args:
            - '-nginx.scrape-uri=http://localhost:8080/basic_status'
          ports:
          - containerPort: 9113
            name: nginx-exporter
          imagePullPolicy: IfNotPresent
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        location = /basic_status {
            stub_status;
        }
    }
