apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: nginx
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: nginx-exporter
