repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io
releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable/nginx
    version: 1.41.3
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 2.13.2
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - expose.ingress.hosts.core: harbor.84.252.150.117.nip.io
