apiVersion: v1
kind: Pod
metadata:
  name: web
  labels: 
    name: web
spec:
  initContainers:
  - name: generate-html
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh ']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
  containers: 
  - name: web
    image: puzyrevyaroslav/nginx_otus_hw_1:latest
    # readinessProbe:
    #   httpGet:
    #     path: /index.html
    #     port: 80
    livenessProbe:
      tcpSocket:
        port: 8000
    imagePullPolicy: Always
    volumeMounts:
    - name: app
      mountPath: /app
    - name: cache
      mountPath: /var/cache/nginx
    - name: pid
      mountPath: /run
    - name: logs
      mountPath: /var/log/nginx
  volumes:
  - name: app
    emptyDir: {}
  - name: cache
    emptyDir: {}
  - name: pid
    emptyDir: {}
  - name: logs
    emptyDir: {}
